### ISSUE TITLE
Running tests locally fails: too many tries for lightning-rpc

### ISSUE THREAD

**Issue by grubles** [ElementsProject/peerswap#221]
I've set up `nix` on my machine to replicate the github CI environment so I can test changes locally. However, some tests fail that succeed on the github CI:

```
FAIL: Test_RestoreFromPassedCSV (60.50s)
FAIL: Test_Recover_PassedSwap_LBTC (54.62s)
FAIL: Test_Recover_PassedSwap_BTC (60.36s)
FAIL: Test_ClnLnd_Liquid_SwapIn (0.00s)
```

The first three fail with this error message about `lightning-rpc`:

```
    recovery_test.go:239: 
                Error Trace:    /home/user/builds/peerswap/test/recovery_test.go:239
                Error:          Received unexpected error:
                                to many retries: Unable to dial socket /run/user/1000/Test_Recover_PassedSwap_BTC231816928/001/clightning-f4B6o/regtest/lightning-rpc:di
al unix /run/user/1000/Test_Recover_PassedSwap_BTC231816928/001/clightning-f4B6o/regtest/lightning-rpc: connect: connection refused
```

@wtogami suspects there is a race condition occurring that I might have introduced in #219 but even if you try older commits (I even tried as far back as 59dd5726f5ceed0435375ac3a682a724a0724fee) , the error will occur. 

Notably, if I increase the timeout in `testframework/clightning.go` from 10 to 30, those first three tests will pass.

**Comment by wtogami** [comment]
I think multiple flakes were possible after #215. Tests are beginning too soon during startup like #222 ?

**Comment by nepet** [comment]
Ok, It seems that this one originates from the test-framework, rather than from peerswap itself. Line 239 in `test/recovery_test.go` restarts a formerly shutdown node and we get an error `to many retries: ...` which is thrown in line 128 of `testframework/clightning.go`

Cranking up the amount of retries from 10 to 30 seems reasonable to me if it works for you. We could even add some more retries, as we try to connect to the socket every 0.5s.

**Comment by grubles** [comment]
I did notice increasing the retries helped things locally but will that affect the github CI? The #219 block watcher ticker change from 0.5 seconds to 15 seconds seemed to break a few tests.

**Comment by nepet** [comment]
Mh, we could use an environmental variable to set the block watcher tick time and default to 15s if nothing is set. We could use the env var to set the ticker duration back to 0.5 seconds on tests.

**Comment by YusukeShimizu** [comment]
Since the block watcher tick time is set back to 0.5s by https://github.com/ElementsProject/peerswap/pull/220, there seems to be no current need to use environment variables.

To make the number of retries separately configurable for github CI and local, I think there is an option to use an environment variable to the amount of retries.

**Comment by grubles** [comment]
I re-ran the tests locally and it seems to have been fixed. Closing for now.
