### ISSUE TITLE
Add date + timestamp to peerswap-panic-log filename

### ISSUE THREAD

**Issue by wtogami** [ElementsProject/peerswap#75]
peerswap-panic-log is currently a little confusing because it appends unrelated tracebacks back to back. We should do the same thing as CLN where the datetimestamp is at the end of each file.

**Comment by nepet** [comment]
This might be harder than I initially thought off. We use `dup2` to duplicate the `stderr` to a file for panic logs. Panic itself in golang unfortunately has no timestamps. One solution that might be a bit messy but better than nothing for the moment would be to write a divider (line with timestamp e.g.) into the panic log on startup.

What do you think about this rather messy solution?

**Comment by wtogami** [comment]
That's pretty messy but if we can't fix glightning to instead pass tracebacks to the normal logger that would be an improvement over this.

**Comment by wtogami** [comment]
Better idea: new panic log per panic. Include datestamp at the end of the filename in the same way CLN does it. e.g. `crash.log.20220708152348`

**Comment by kallerosenbaum** [comment]
@wtogami I'm looking into this. With your suggestion. the timestamp would be when the plugin started, not when it crashed. But it will help you distinguish between crashes at least, so that's better than what we currently have. Would this still be desirable? A pretty big downside is that we'll create an empty file for each time we start/stop the plugin and there's no panics. We could somewhat fix this by cleaning up empty files upon next start.

Another approach, that I think is the least bad option, could be to move away the current `peerswap-panic-log` file into a file with a timestamp suffix when we start, if it contains data. This is very similar to @nepet's idea to simply add a divider.

Setting a timestamp when the actual panic occurs seems hard. I haven't figured out how. The file is opened and closed in the main goroutine, but the panic usually occurs in another goroutine, namely the one created by glightning that calls `Call()`. We can't `recover` from when another goroutine panics so cleanup code in the main goroutine is never called. For example, the `Close` function returned from `setPanicLogger` is never called when a command panics.

**Comment by wtogami** [comment]
Divider line printing the date + timestamp in UTC for each crash would be adequate.
