### ISSUE TITLE
Sanity check channel balance prior to swap

### ISSUE THREAD

**Issue by wtogami** [ElementsProject/peerswap#81]
Prior to starting a swap, and again prior to sending, check the channel's max htlc limit to verify that the requested swap would actually be possible. Print informative error messages otherwise.

Related: #73

**Comment by nepet** [comment]
## Why
So this issue is a little bit paranoid but we want to do everything we can to avoid canceled swaps, especially swap-out swaps as the `responder` is in charge of the on-chain part.
The following assumes a swap-out but same applies symmetrically for a swap-in:
Currently we only check that we have enough local balance (`our_amount_msat`) to perform the swap. This check is not strong enough as we could have set a `htlc_maximum_msat` that is below our local balance.

## Solution
We want to check that `min(htlc_maximum_msat, our_amount_msat) > swap_amt_msat + fees`
Best place to check that would be after we received the `swap_out_agreement` that contains the "fee_invoice". We may still want to perform the same check without the fees before we initiate a swap.

**Comment by wtogami** [comment]
Nothing is currently broken without this but this would be a nice to have because it prevents events that would immediately fail from adding things to the database.
